language: node_js
node_js:
  - '0.12'
script:
  - npm run coverage
after_script:
  - npm install codeclimate-test-reporter && cat coverage/lcov.info | codeclimate-test-reporter
deploy:
  provider: heroku
  api_key: $HEROKU_AUTH_TOKEN
